### ISSUE TITLE
Graceful handling of Trailing Slash

### ISSUE THREAD

**Issue by benbitrise** [bitrise-steplib/bitrise-step-build-router-wait#12]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.12.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

`build_artifacts_save_path` isn't smart about a missing trailing slash.
Say I provide `/path/to/dir` as my save path. The step will save `artifact.file` to `/path/to/dirartifact.file`

This is inconvenient because the common input is `$BITRISE_DEPLOY_DIR`, which, by default, lacks a trailing slash.

### Bitrise info

- Build URL: https://app.bitrise.io/build/6cffbbdbe2507753#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_
- Log: 

<details>
  <pre>
Downloaded: xcode-test-results-BitriseTest.html to path /Users/vagrant/deploy
  </pre>
</details>

### Steps to reproduce

1. Set `$BITRISE_DEPLOY_DIR` as your `build_artifacts_save_path`

**Comment by ofalvai** [comment]
Fixed in #13, closing this issue.
