### ISSUE TITLE
error: json: cannot unmarshal array into Go struct

### ISSUE THREAD

**Issue by asos-petergoldsmith** [bitrise-steplib/bitrise-step-build-router-wait#3]
We're seeing the following for the router wait step:
```
An error occoured: failed to get build info, error: failed to decode response, body: <redacted>
, error: json: cannot unmarshal array into Go struct field buildResponse.data of type bitrise.Build
```

Any guidance on debugging / providing you more info?

**Comment by tamasbazs** [comment]
Hi there,
Thanks for reporting the issue! Could you send me the URL of the build?

**Comment by asos-petergoldsmith** [comment]
So, after some digging we figured out what was going on.
We were feeding `BuildSlugs` a variable that had an empty line first, so it looked like the following:
```

356418da45df5e61
```

We have identified that the https://github.com/bitrise-steplib/bitrise-step-build-router-start doesn't append build slugs to the same variable correctly (it appears to just squash the previous value). I'll see if I can submit a PR for https://github.com/bitrise-steplib/bitrise-step-build-router-start

**Comment by asos-petergoldsmith** [comment]
Would be nice if this step was a bit looser in its input, so that it could deal with an empty line, but understand that is not really within this steps api contract
