### ISSUE TITLE
Wait should have a time-out setting

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/bitrise-step-build-router-wait#4]
When using this step along with https://github.com/bitrise-steplib/bitrise-step-build-router-start, it's now possible to create a deadlock. For example, let's say I have two concurrencies, and I have a workflow `master` that starts/waits for `slave` workflow. If I start two `master` builds at nearly the same time, they will use both the concurrencies and the two `slave` workflows will then be "waiting" for a free concurrency, which never happens. 

It's not ideal but if waiting at least timed-out after a user-specified amount of time, then the deadlock would free up. Yes the build would fail but at least it wouldn't block other builds.

**Comment by godrei** [comment]
Hi, thanks for the issue report, task scheduled to fix this.

**Comment by godrei** [comment]
Hi, we have discussed this issue with the team and it can not be properly solved by the step itself.
We'll do a higher level architecture revision regarding the build starts which would fix this issue.
Until the fix, please run your builds after each other and sorry for the inconvenience.
